# Generated by Django 6.1 on 2026-08-31 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Equipment',
        ),
    ]
