# Generated by Django 6.1 on 2026-08-31 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0002_rename_member_equipment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipment',
        ),
    ]
