# Generated by Django 6.1 on 2026-08-31 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipments', '0003_delete_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('register_number', models.IntegerField()),
                ('register_date', models.DateField()),
            ],
        ),
    ]
